name: camscanner
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  pdf: ^3.7.1
  path_provider: ^2.1.2
  printing: ^5.12.0
  permission_handler: ^11.3.1
  device_info_plus: ^9.1.2
  image_picker: ^1.0.8
  image_cropper: ^6.0.0
  image: ^4.1.7
  photo_view: ^0.15.0
  provider: ^6.1.2
  simple_fx: ^1.0.1
  google_mlkit_document_scanner: ^0.2.0
  screenshot: ^2.5.0
  file_picker: ^6.0.0
  pdf_render: ^1.4.7
  google_fonts: ^6.2.1
  google_generative_ai: ^0.4.3
  http: ^1.2.1
  flutter_rating_bar: ^4.0.1
  speech_to_text: ^6.6.2
  # flutter_launcher_icons: ^0.13.1  


# flutter_launcher_icons:
#   android: true
#   ios: true
#   image_path: "assets/imges/logo.jpg"
#   adaptive_icon_foreground: "assets/imges/logo.jpg"
#   adaptive_icon_background: "#000000"


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/imges/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
